version: '3'

services:
  app:
    image: kevinduy/reactjs
    tty: true
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
      - "9099:9099"
      - "5001:5001"
      - "9199:9199"
      - "6006:6006"
      - "9005:9005"
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .docker/db:/data/db